services:
  wanndarfichheim:
    build: .
    container_name: wanndarfichheim
    restart: unless-stopped
    user: "101:101"
    read_only: true
    tmpfs:
      - /tmp:mode=1777
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 32M
        reservations:
          cpus: "0.01"
          memory: 16M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - web-services

networks:
  web-services:
    external: true
